### ISSUE TITLE
Defender Surface Attack Surface Reduction (ASR) rules and FSLogix

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/architecture-center#2915]
Using the default [SetTempToLocalPath](https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference#settemptolocalpath) setting, Defender [ASR](https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/attack-surface-reduction) was blocking javascript files required for the office sign-in page to load.

#2107060040003922 - FSLogix
#26280461 - Defender

It's unclear at the moment from the the two tickets above if defender is having an issue because FSLogix is storing the INetCache files in a different location and I hope to have more clarity before the end of the week as to whether the current guidance is to add additional exclusions when FSLogix and Office are used together, or if Defender wants to address this issue from their end.

At the very least, if anyone has problems with office sign-in's adding the following exclusions may resolve your issue:
> C:\Users\*\INetCache\IE\*\CommonDiagnostics?.js
> C:\Users\*\INetCache\IE\*\ConvergedLogin_PCore_?.js
> C:\Users\*\INetCache\IE\*\convergedlogin_ppassword_?.js
> C:\Users\*\INetCache\IE\*\convergedlogin_ptiles_?.js
> C:\Users\*\INetCache\IE\*\frameworksupport.min_?.js
> C:\Users\*\INetCache\IE\*\hrd.min?.js
> C:\Users\*\INetCache\IE\*\jsonstrings?.js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6386653c-9f82-1ea7-8f29-377be4e5e3b7
* Version Independent ID: a5db2b47-afaf-5917-40cd-740168cad8b6
* Content: [FSLogix for the enterprise - Azure Architecture Guide](https://docs.microsoft.com/en-us/azure/architecture/example-scenario/wvd/windows-virtual-desktop-fslogix#antivirus-exclusions)
* Content Source: [docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml](https://github.com/microsoftdocs/architecture-center/blob/master/docs/example-scenario/wvd/windows-virtual-desktop-fslogix.yml)
* Service: **architecture-center**
* Sub-service: **azure-guide**
* GitHub Login: @christiaanbrinkhoff
* Microsoft Alias: **pnp**

**Comment by david-stanford** [comment]
Thanks for reporting - this issue is under review. This is a Microsoft Internal DevOps Bug ID # <a href=https://ceapex.visualstudio.com//pnp/_workitems/edit/454544/>454544</a>

**Comment by jonwbstr** [comment]
Engineer assigned to the Defender ticket says the issue has been resolved internally, so I am closing this. Hopefully it stays fixed :)

**Comment by JonathanForrester** [comment]
This issue may not be fixed anymore.

One of my customers is still having this problem in a recently provisioned environment. They are using FSLogix 2.9.797962170 and Windows 10 Enterprise for Virtual Desktops 21H2 with the 2022-02 Cumulative Update installed (build 19044.1566).

When ASR rule 3b576869-a4ec-4529-8536-b80a7769e899 (Block Office applications from creating executable content) is enabled, and the INetCache folder is redirected to C:\Users\local_<USERNAME>, the sign in page in Excel, Word, and other applications will not load.

The event logs indicate that the ASR rule named "Block Office applications from creating executable content" blocks the following items from running:

C:\Users\local_<USERNAME>\INetCache\IE\<FOLDER>\CommonDiagnostics[1].js
C:\Users\local_<USERNAME>\INetCache\IE\<FOLDER>\knockout-3.4.2[1].js
C:\Users\local_<USERNAME>\INetCache\IE\<FOLDER>\jsonstrings[1].js
C:\Users\local_<USERNAME>\INetCache\IE\<FOLDER>\jquery-1.12.4.1.min[1].js
C:\Users\local_<USERNAME>\INetCache\IE\<FOLDER>\hrd.min[1].js

If the INetCache folder is set to its default location this issue does not appear to occur.

**Comment by reph-con** [comment]
This issue may not be fixed: My solution was: Set ASR Rule 3b576869-a4ec-4529-8536-b80a7769e899 from block to audit, Warn or off.
Plsss fix this issue. thank you

**Comment by Grassyhopper** [comment]
I dont think this issue is fixed I am seeing the same as the above

**Comment by brink668** [comment]
> I dont think this issue is fixed I am seeing the same as the above

Hi! Which ASR rule is hitting / blocking .js files?

I am having similar issues but from Outlook.exe with addins that load .js files as well.

see my post here:
https://techcommunity.microsoft.com/t5/microsoft-defender-for-endpoint/asr-behavior-changes-blocking-under-user-context-now/m-p/3589618

**Comment by maryarras** [comment]
We have been experiencing this issue, as well. We did not see that setting a filter prevented the rule from firing, though we did not try this specific set of filters. We are currently having to run in Audit mode on this ASR rule, as well.

**Comment by Yippee-Ki-el** [comment]
Did anyone get any further with this? we are hitting the exact same issue and dont really want to put the offending rule in Audit mode

**Comment by JeroenP87** [comment]
Same issue here, AVD Windows 11 22H2 with fslogix.

**Comment by emergencynap** [comment]
Still not fixed
